import Contest from "@/components/contest";
import Experience from "@/components/experience";
import Projects from "@/components/projects";
import Sidebar from "@/components/sidebar";
import Summery from "@/components/summary";
import Head from "next/head";

export default function Home() {
  return (
    <div className="rounded-lg bg-slate-50">
      <Head>
        <title>Mamun-Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-[792px] h-[1400px] mx-auto  mb-10  bg-slate-200 pr-4 rounded-lg">
        {/* <div className="flex "> */}
        <Sidebar />
        <div>
          <div className="bg-teal-900 h-16 rounded-r-full py-2 text-white  text-xl w-96  mt-16">
            <p className="font-semibold ml-14">MD AL MAMUN MIM</p>
            <p className="text-sm ml-14">Junior Software Engineer</p>
          </div>
          <div className="ml-14 flex-col space-y-4">
            <Summery />
            <Experience />
            <Contest />
            <Projects />
          </div>
        </div>
      </div>
    </div>
  )
}
